apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin4.fullname" . }}
  namespace: default
spec:
  selector:
    app: {{ include "pgadmin4.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
