apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin4.fullname" . }}-pwd
  namespace: default
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: {{ include "pgadmin4.password" . | b64enc | quote }}